In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)

# Apply vs Transform
- There are improper explanations out there on the web. 

## Let us Understand two types of functions

- A function which takes a list of values and returns list of values of the same length
    - In pandas world, a series(row/column) is a list of values and return is a series(new rows/columns)
    - In pandas world, a data frame is a list of series
- A function which takes a list of values and returns a scalar 
        - In pandas world , a scalar can be something like sum()/mean() of all values
        - In pandas world, a data frame is a list of series

## APPLY
- APPLY on either rows/columns => series accepts both type of functions
        1. You can use **result_type='broadcast'** if dimensions are reduced in second type of function
- APPLY if a dataframe is passed in (group by returns groups of DF) accepts both type of functions
        2. There is **NO** result_type='broadcast' if dimensions are reduced in second type of function
        3. Refer GroupBy.apply
        
## TRANSFORM
- TRANSFORM accepts only **first type** of function.
        - TRANSFORM accepts second type of function only when you pass in a DataFrame, it automatically broadcasts results to each group 
- TRANSFORM  if a dataframe is passed in (group by returns groups of DF) ,for each group,the function is applied on a series(rows/columns) and the result is broad casted if the dimensions are reduced
- EFFECTIVELY transform is applicable for input type - Series. **transform on DataFrameGroupBy** object does the magic of 
broadcasting 
   - **DataFrameGroupBy.transform**

In [5]:
def add(x):
    print('----')
    print(f"Passed in -- {type(x)}")
    print(x)
    print(f"Passed in length {len(x)} return length {len(x+10)}")
    print('----')
    return x+10

In [6]:
df.apply(add) #default axis=0 => columns

----
Passed in -- <class 'pandas.core.series.Series'>
0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64
Passed in length 150 return length 150
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal width (cm), Length: 150, dtype: float64
Passed in length 150 return length 150
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal length (cm), Length: 150, dtype: float64
Passed in length 150 return length 150
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal width (cm), Length: 150, dtype: float64
Passed in length 150 return length 150
----

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 15.1              13.5               11.4              10.2
1                 14.9              13.0               11.4              10.2
2                 14.7              13.2               11.3              10.2
3                 14.6              13.1               11.5              10.2
4                 15.0              13.6               11.4              10.2
..                 ...               ...                ...               ...
145               16.7              13.0               15.2              12.3
146               16.3              12.5               15.0              11.9
147               16.5              13.0               15.2              12.0
148               16.2              13.4               15.4              12.3
149               15.9              13.0               15.1              11.8

[150 rows x 4 columns]

In [7]:
df.transform(add) #default axis=0 => columns

----
Passed in -- <class 'pandas.core.series.Series'>
0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64
Passed in length 150 return length 150
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal width (cm), Length: 150, dtype: float64
Passed in length 150 return length 150
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal length (cm), Length: 150, dtype: float64
Passed in length 150 return length 150
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal width (cm), Length: 150, dtype: float64
Passed in length 150 return length 150
----

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 15.1              13.5               11.4              10.2
1                 14.9              13.0               11.4              10.2
2                 14.7              13.2               11.3              10.2
3                 14.6              13.1               11.5              10.2
4                 15.0              13.6               11.4              10.2
..                 ...               ...                ...               ...
145               16.7              13.0               15.2              12.3
146               16.3              12.5               15.0              11.9
147               16.5              13.0               15.2              12.0
148               16.2              13.4               15.4              12.3
149               15.9              13.0               15.1              11.8

[150 rows x 4 columns]

In [33]:
def my_mean(x):
    print('----')
    print(f"Passed in -- {type(x)}")
    print(x)
    print(f"passed in length {len(x)} return length =1 scalar {x.mean().shape}")
    print(f"return value {x.mean()}")
    print('----')
    return x.mean()

In [40]:
df.apply(my_mean) #default axis=0 => columns

#For every column only one scalar(mean) is returned

----
Passed in -- <class 'pandas.core.series.Series'>
0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64
passed in length 150 return length =1 scalar ()
return value 5.843333333333334
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal width (cm), Length: 150, dtype: float64
passed in length 150 return length =1 scalar ()
return value 3.0573333333333337
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal length (cm), Length: 150, dtype: float64
passed in length 150 return length =1 scalar ()
return value 3.7580000000000005
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal width (cm), Length: 150, dtype: float64
passed in length 150 return length =1 scalar ()
return value 1.1993333333333336
----

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [41]:
df.apply(my_mean,result_type='broadcast')

----
Passed in -- <class 'pandas.core.series.Series'>
0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64
passed in length 150 return length =1 scalar ()
return value 5.843333333333334
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal width (cm), Length: 150, dtype: float64
passed in length 150 return length =1 scalar ()
return value 3.0573333333333337
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal length (cm), Length: 150, dtype: float64
passed in length 150 return length =1 scalar ()
return value 3.7580000000000005
----
----
Passed in -- <class 'pandas.core.series.Series'>
0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal width (cm), Length: 150, dtype: float64
passed in length 150 return length =1 scalar ()
return value 1.1993333333333336
----

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             5.843333          3.057333              3.758          1.199333
1             5.843333          3.057333              3.758          1.199333
2             5.843333          3.057333              3.758          1.199333
3             5.843333          3.057333              3.758          1.199333
4             5.843333          3.057333              3.758          1.199333
..                 ...               ...                ...               ...
145           5.843333          3.057333              3.758          1.199333
146           5.843333          3.057333              3.758          1.199333
147           5.843333          3.057333              3.758          1.199333
148           5.843333          3.057333              3.758          1.199333
149           5.843333          3.057333              3.758          1.199333

[150 rows x 4 columns]

In [10]:
df.transform(my_mean) #default axis=0 => columns
print("Transform does not accept change in length of the given axis.here default axis =0" )

<class 'pandas.core.series.Series'>
passed in length 150 return length =1 scalar ()
<class 'pandas.core.series.Series'>
passed in length 150 return length =1 scalar ()
<class 'pandas.core.series.Series'>
passed in length 150 return length =1 scalar ()
<class 'pandas.core.series.Series'>
passed in length 150 return length =1 scalar ()

ValueError: Function did not transform

In [11]:
df[df.columns[1]].unique()
df[df.columns[1]].nunique()
df[df.columns[1]].value_counts()

3.0    26
2.8    14
3.2    13
3.4    12
3.1    11
2.9    10
2.7     9
2.5     8
3.3     6
3.8     6
3.5     6
2.6     5
2.3     4
3.6     4
3.7     3
2.2     3
2.4     3
3.9     2
2.0     1
4.4     1
4.0     1
4.2     1
4.1     1
Name: sepal width (cm), dtype: int64

In [15]:
df.groupby(df.columns[1]).apply(add).sort_values(df.columns[1],ascending=True)

## Applies for each group

----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
60                5.0               2.0                3.5               1.0
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
62                 6.0               2.2                4.0               1.0
68                 6.2               2.2                4.5               1.5
119                6.0               2.2                5.0               1.5
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
41                4.5               2.3                1.3               0.3
53                5.5               2.3                4.0               1.3
87                6.3               2.3                4.4               1.3
93                5.0               2.3                3.3               1.0
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
57                4.9               2.4                3.3               1.0
80                5.5               2.4                3.8               1.1
81                5.5               2.4                3.7               1.0
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
69                 5.6               2.5                3.9               1.1
72                 6.3               2.5                4.9               1.5
89                 5.5               2.5                4.0               1.3
98                 5.1               2.5                3.0               1.1
106                4.9               2.5                4.5               1.7
108                6.7               2.5                5.8               1.8
113                5.7               2.5                5.0               2.0
146                6.3               2.5                5.0               1.9
Passed in length 8 return length 8
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
79                 5.7               2.6                3.5               1.0
90                 5.5               2.6                4.4               1.2
92                 5.8               2.6                4.0               1.2
118                7.7               2.6                6.9               2.3
134                6.1               2.6                5.6               1.4
Passed in length 5 return length 5
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
59                 5.2               2.7                3.9               1.4
67                 5.8               2.7                4.1               1.0
82                 5.8               2.7                3.9               1.2
83                 6.0               2.7                5.1               1.6
94                 5.6               2.7                4.2               1.3
101                5.8               2.7                5.1               1.9
111                6.4               2.7                5.3               1.9
123                6.3               2.7                4.9               1.8
142                5.8               2.7                5.1               1.9
Passed in length 9 return length 9
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
54                 6.5               2.8                4.6               1.5
55                 5.7               2.8                4.5               1.3
71                 6.1               2.8                4.0               1.3
73                 6.1               2.8                4.7               1.2
76                 6.8               2.8                4.8               1.4
99                 5.7               2.8                4.1               1.3
114                5.8               2.8                5.1               2.4
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
126                6.2               2.8                4.8               1.8
128                6.4               2.8                5.6               2.1
130                7.4               2.8                6.1               1.9
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
Passed in length 14 return length 14
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
58                 6.6               2.9                4.6               1.3
63                 6.1               2.9                4.7               1.4
64                 5.6               2.9                3.6               1.3
74                 6.4               2.9                4.3               1.3
78                 6.0               2.9                4.5               1.5
96                 5.7               2.9                4.2               1.3
97                 6.2               2.9                4.3               1.3
103                6.3               2.9                5.6               1.8
107                7.3               2.9                6.3               1.8
Passed in length 10 return length 10
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                  4.9               3.0                1.4               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
25                 5.0               3.0                1.6               0.2
38                 4.4               3.0                1.3               0.2
45                 4.8               3.0                1.4               0.3
61                 5.9               3.0                4.2               1.5
66                 5.6               3.0                4.5               1.5
75                 6.6               3.0                4.4               1.4
77                 6.7               3.0                5.0               1.7
84                 5.4               3.0                4.5               1.5
88                 5.6               3.0                4.1               1.3
91                 6.1               3.0                4.6               1.4
95                 5.7               3.0                4.2               1.2
102                7.1               3.0                5.9               2.1
104                6.5               3.0                5.8               2.2
105                7.6               3.0                6.6               2.1
112                6.8               3.0                5.5               2.1
116                6.5               3.0                5.5               1.8
127                6.1               3.0                4.9               1.8
129                7.2               3.0                5.8               1.6
135                7.7               3.0                6.1               2.3
138                6.0               3.0                4.8               1.8
145                6.7               3.0                5.2               2.3
147                6.5               3.0                5.2               2.0
149                5.9               3.0                5.1               1.8
Passed in length 26 return length 26
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
3                  4.6               3.1                1.5               0.2
9                  4.9               3.1                1.5               0.1
30                 4.8               3.1                1.6               0.2
34                 4.9               3.1                1.5               0.2
52                 6.9               3.1                4.9               1.5
65                 6.7               3.1                4.4               1.4
86                 6.7               3.1                4.7               1.5
137                6.4               3.1                5.5               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
Passed in length 11 return length 11
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
2                  4.7               3.2                1.3               0.2
29                 4.7               3.2                1.6               0.2
35                 5.0               3.2                1.2               0.2
42                 4.4               3.2                1.3               0.2
47                 4.6               3.2                1.4               0.2
50                 7.0               3.2                4.7               1.4
51                 6.4               3.2                4.5               1.5
70                 5.9               3.2                4.8               1.8
110                6.5               3.2                5.1               2.0
115                6.4               3.2                5.3               2.3
120                6.9               3.2                5.7               2.3
125                7.2               3.2                6.0               1.8
143                6.8               3.2                5.9               2.3
Passed in length 13 return length 13
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
23                 5.1               3.3                1.7               0.5
49                 5.0               3.3                1.4               0.2
56                 6.3               3.3                4.7               1.6
100                6.3               3.3                6.0               2.5
124                6.7               3.3                5.7               2.1
144                6.7               3.3                5.7               2.5
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
11                 4.8               3.4                1.6               0.2
20                 5.4               3.4                1.7               0.2
24                 4.8               3.4                1.9               0.2
26                 5.0               3.4                1.6               0.4
28                 5.2               3.4                1.4               0.2
31                 5.4               3.4                1.5               0.4
39                 5.1               3.4                1.5               0.2
85                 6.0               3.4                4.5               1.6
136                6.3               3.4                5.6               2.4
148                6.2               3.4                5.4               2.3
Passed in length 12 return length 12
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
17                5.1               3.5                1.4               0.3
27                5.2               3.5                1.5               0.2
36                5.5               3.5                1.3               0.2
40                5.0               3.5                1.3               0.3
43                5.0               3.5                1.6               0.6
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
4                  5.0               3.6                1.4               0.2
22                 4.6               3.6                1.0               0.2
37                 4.9               3.6                1.4               0.1
109                7.2               3.6                6.1               2.5
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
10                5.4               3.7                1.5               0.2
21                5.1               3.7                1.5               0.4
48                5.3               3.7                1.5               0.2
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
44                 5.1               3.8                1.9               0.4
46                 5.1               3.8                1.6               0.2
117                7.7               3.8                6.7               2.2
131                7.9               3.8                6.4               2.0
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
5                 5.4               3.9                1.7               0.4
16                5.4               3.9                1.3               0.4
Passed in length 2 return length 2
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)

14                5.8               4.0                1.2               0.2
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
32                5.2               4.1                1.5               0.1
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
33                5.5               4.2                1.4               0.2
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
15                5.7               4.4                1.5               0.4
Passed in length 1 return length 1
----

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
60                15.0              12.0               13.5              11.0
62                16.0              12.2               14.0              11.0
119               16.0              12.2               15.0              11.5
68                16.2              12.2               14.5              11.5
41                14.5              12.3               11.3              10.3
..                 ...               ...                ...               ...
16                15.4              13.9               11.3              10.4
14                15.8              14.0               11.2              10.2
32                15.2              14.1               11.5              10.1
33                15.5              14.2               11.4              10.2
15                15.7              14.4               11.5              10.4

[150 rows x 4 columns]

In [31]:
apply_group=df.groupby(df.columns[1]).apply(my_mean)
print(apply_group.shape)
print(apply_group)

----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
60                5.0               2.0                3.5               1.0
passed in length 1 return length =1 scalar (4,)
return valuesepal length (cm)    5.0
sepal width (cm)     2.0
petal length (cm)    3.5
petal width (cm)     1.0
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
62                 6.0               2.2                4.0               1.0
68                 6.2               2.2                4.5               1.5
119                6.0               2.2                5.0               1.5
passed in length 3 return length =1 scalar (4,)
return valuesepal length (cm)    6.066667
sepal width (cm)     2.200000
petal length (cm)    4.500000
petal width (cm)     1.333333
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
41                4.5               2.3                1.3               0.3
53                5.5               2.3                4.0               1.3
87                6.3               2.3                4.4               1.3
93                5.0               2.3                3.3               1.0
passed in length 4 return length =1 scalar (4,)
return valuesepal length (cm)    5.325
sepal width (cm)     2.300
petal length (cm)    3.250
petal width (cm)     0.975
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
57                4.9               2.4                3.3               1.0
80                5.5               2.4                3.8               1.1
81                5.5               2.4                3.7               1.0
passed in length 3 return length =1 scalar (4,)
return valuesepal length (cm)    5.300000
sepal width (cm)     2.400000
petal length (cm)    3.600000
petal width (cm)     1.033333
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
69                 5.6               2.5                3.9               1.1
72                 6.3               2.5                4.9               1.5
89                 5.5               2.5                4.0               1.3
98                 5.1               2.5                3.0               1.1
106                4.9               2.5                4.5               1.7
108                6.7               2.5                5.8               1.8
113                5.7               2.5                5.0               2.0
146                6.3               2.5                5.0               1.9
passed in length 8 return length =1 scalar (4,)
return valuesepal length (cm)    5.7625
sepal width (cm)     2.5000
petal length (cm)    4.5125
petal width (cm)     1.5500
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
79                 5.7               2.6                3.5               1.0
90                 5.5               2.6                4.4               1.2
92                 5.8               2.6                4.0               1.2
118                7.7               2.6                6.9               2.3
134                6.1               2.6                5.6               1.4
passed in length 5 return length =1 scalar (4,)
return valuesepal length (cm)    6.16
sepal width (cm)     2.60
petal length (cm)    4.88
petal width (cm)     1.42
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
59                 5.2               2.7                3.9               1.4
67                 5.8               2.7                4.1               1.0
82                 5.8               2.7                3.9               1.2
83                 6.0               2.7                5.1               1.6
94                 5.6               2.7                4.2               1.3
101                5.8               2.7                5.1               1.9
111                6.4               2.7                5.3               1.9
123                6.3               2.7                4.9               1.8
142                5.8               2.7                5.1               1.9
passed in length 9 return length =1 scalar (4,)
return valuesepal length (cm)    5.855556
sepal width (cm)     2.700000
petal length (cm)    4.622222
petal width (cm)     1.555556
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
54                 6.5               2.8                4.6               1.5
55                 5.7               2.8                4.5               1.3
71                 6.1               2.8                4.0               1.3
73                 6.1               2.8                4.7               1.2
76                 6.8               2.8                4.8               1.4
99                 5.7               2.8                4.1               1.3
114                5.8               2.8                5.1               2.4
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
126                6.2               2.8                4.8               1.8
128                6.4               2.8                5.6               2.1
130                7.4               2.8                6.1               1.9
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
passed in length 14 return length =1 scalar (4,)
return valuesepal length (cm)    6.335714
sepal width (cm)     2.800000
petal length (cm)    5.042857
petal width (cm)     1.707143
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
58                 6.6               2.9                4.6               1.3
63                 6.1               2.9                4.7               1.4
64                 5.6               2.9                3.6               1.3
74                 6.4               2.9                4.3               1.3
78                 6.0               2.9                4.5               1.5
96                 5.7               2.9                4.2               1.3
97                 6.2               2.9                4.3               1.3
103                6.3               2.9                5.6               1.8
107                7.3               2.9                6.3               1.8
passed in length 10 return length =1 scalar (4,)
return valuesepal length (cm)    6.06
sepal width (cm)     2.90
petal length (cm)    4.35
petal width (cm)     1.32
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                  4.9               3.0                1.4               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
25                 5.0               3.0                1.6               0.2
38                 4.4               3.0                1.3               0.2
45                 4.8               3.0                1.4               0.3
61                 5.9               3.0                4.2               1.5
66                 5.6               3.0                4.5               1.5
75                 6.6               3.0                4.4               1.4
77                 6.7               3.0                5.0               1.7
84                 5.4               3.0                4.5               1.5
88                 5.6               3.0                4.1               1.3
91                 6.1               3.0                4.6               1.4
95                 5.7               3.0                4.2               1.2
102                7.1               3.0                5.9               2.1
104                6.5               3.0                5.8               2.2
105                7.6               3.0                6.6               2.1
112                6.8               3.0                5.5               2.1
116                6.5               3.0                5.5               1.8
127                6.1               3.0                4.9               1.8
129                7.2               3.0                5.8               1.6
135                7.7               3.0                6.1               2.3
138                6.0               3.0                4.8               1.8
145                6.7               3.0                5.2               2.3
147                6.5               3.0                5.2               2.0
149                5.9               3.0                5.1               1.8
passed in length 26 return length =1 scalar (4,)
return valuesepal length (cm)    6.015385
sepal width (cm)     3.000000
petal length (cm)    4.234615
petal width (cm)     1.403846
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
3                  4.6               3.1                1.5               0.2
9                  4.9               3.1                1.5               0.1
30                 4.8               3.1                1.6               0.2
34                 4.9               3.1                1.5               0.2
52                 6.9               3.1                4.9               1.5
65                 6.7               3.1                4.4               1.4
86                 6.7               3.1                4.7               1.5
137                6.4               3.1                5.5               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
passed in length 11 return length =1 scalar (4,)
return valuesepal length (cm)    6.036364
sepal width (cm)     3.100000
petal length (cm)    3.790909
petal width (cm)     1.245455
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
2                  4.7               3.2                1.3               0.2
29                 4.7               3.2                1.6               0.2
35                 5.0               3.2                1.2               0.2
42                 4.4               3.2                1.3               0.2
47                 4.6               3.2                1.4               0.2
50                 7.0               3.2                4.7               1.4
51                 6.4               3.2                4.5               1.5
70                 5.9               3.2                4.8               1.8
110                6.5               3.2                5.1               2.0
115                6.4               3.2                5.3               2.3
120                6.9               3.2                5.7               2.3
125                7.2               3.2                6.0               1.8

143                6.8               3.2                5.9               2.3
passed in length 13 return length =1 scalar (4,)
return valuesepal length (cm)    5.884615
sepal width (cm)     3.200000
petal length (cm)    3.753846
petal width (cm)     1.261538
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
23                 5.1               3.3                1.7               0.5
49                 5.0               3.3                1.4               0.2
56                 6.3               3.3                4.7               1.6
100                6.3               3.3                6.0               2.5
124                6.7               3.3                5.7               2.1
144                6.7               3.3                5.7               2.5
passed in length 6 return length =1 scalar (4,)
return valuesepal length (cm)    6.016667
sepal width (cm)     3.300000
petal length (cm)    4.200000
petal width (cm)     1.566667
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
11                 4.8               3.4                1.6               0.2
20                 5.4               3.4                1.7               0.2
24                 4.8               3.4                1.9               0.2
26                 5.0               3.4                1.6               0.4
28                 5.2               3.4                1.4               0.2
31                 5.4               3.4                1.5               0.4
39                 5.1               3.4                1.5               0.2
85                 6.0               3.4                4.5               1.6
136                6.3               3.4                5.6               2.4
148                6.2               3.4                5.4               2.3
passed in length 12 return length =1 scalar (4,)
return valuesepal length (cm)    5.316667
sepal width (cm)     3.400000
petal length (cm)    2.466667
petal width (cm)     0.716667
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
17                5.1               3.5                1.4               0.3
27                5.2               3.5                1.5               0.2
36                5.5               3.5                1.3               0.2
40                5.0               3.5                1.3               0.3
43                5.0               3.5                1.6               0.6
passed in length 6 return length =1 scalar (4,)
return valuesepal length (cm)    5.150000
sepal width (cm)     3.500000
petal length (cm)    1.416667
petal width (cm)     0.300000
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
4                  5.0               3.6                1.4               0.2
22                 4.6               3.6                1.0               0.2
37                 4.9               3.6                1.4               0.1
109                7.2               3.6                6.1               2.5
passed in length 4 return length =1 scalar (4,)
return valuesepal length (cm)    5.425
sepal width (cm)     3.600
petal length (cm)    2.475
petal width (cm)     0.750
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
10                5.4               3.7                1.5               0.2
21                5.1               3.7                1.5               0.4
48                5.3               3.7                1.5               0.2
passed in length 3 return length =1 scalar (4,)
return valuesepal length (cm)    5.266667
sepal width (cm)     3.700000
petal length (cm)    1.500000
petal width (cm)     0.266667
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
44                 5.1               3.8                1.9               0.4
46                 5.1               3.8                1.6               0.2
117                7.7               3.8                6.7               2.2
131                7.9               3.8                6.4               2.0
passed in length 6 return length =1 scalar (4,)
return valuesepal length (cm)    6.1
sepal width (cm)     3.8
petal length (cm)    3.3
petal width (cm)     0.9
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
5                 5.4               3.9                1.7               0.4
16                5.4               3.9                1.3               0.4
passed in length 2 return length =1 scalar (4,)
return valuesepal length (cm)    5.4
sepal width (cm)     3.9
petal length (cm)    1.5
petal width (cm)     0.4
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
14                5.8               4.0                1.2               0.2
passed in length 1 return length =1 scalar (4,)
return valuesepal length (cm)    5.8
sepal width (cm)     4.0
petal length (cm)    1.2
petal width (cm)     0.2
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
32                5.2               4.1                1.5               0.1
passed in length 1 return length =1 scalar (4,)
return valuesepal length (cm)    5.2
sepal width (cm)     4.1
petal length (cm)    1.5
petal width (cm)     0.1
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
33                5.5               4.2                1.4               0.2
passed in length 1 return length =1 scalar (4,)
return valuesepal length (cm)    5.5
sepal width (cm)     4.2
petal length (cm)    1.4
petal width (cm)     0.2
dtype: float64
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
15                5.7               4.4                1.5               0.4
passed in length 1 return length =1 scalar (4,)
return valuesepal length (cm)    5.7
sepal width (cm)     4.4
petal length (cm)    1.5
petal width (cm)     0.4
dtype: float64
----
(23, 4)
                  sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal width (cm)
2.0                        5.000000               2.0           3.500000
2.2                        6.066667               2.2           4.500000
2.3                        5.325000               2.3           3.250000
2.4                        5.300000               2.4           3.600000
2.5                        5.762500               2.5           4.512500
2.6                        6.160000               2.6           4.880000
2.7                        5.855556               2.7           4.622222
2.8                        6.335714               2.8           5.042857
2.9                        6.060000               2.9           4.350000
3.0                        6.015385               3.0           4.234615
3.1                        6.036364               3.1           3.790909
3.2                        5.884615               3.2           3.753846
3.3                        6.016667               3.3           4.200000
3.4                        5.316667               3.4           2.466667
3.5                        5.150000               3.5           1.416667
3.6                        5.425000               3.6           2.475000
3.7                        5.266667               3.7           1.500000
3.8                        6.100000               3.8           3.300000
3.9                        5.400000               3.9           1.500000
4.0                        5.800000               4.0           1.200000
4.1                        5.200000               4.1           1.500000
4.2                        5.500000               4.2           1.400000
4.4                        5.700000               4.4           1.500000

                  petal width (cm)
sepal width (cm)
2.0                       1.000000
2.2                       1.333333
2.3                       0.975000
2.4                       1.033333
2.5                       1.550000
2.6                       1.420000
2.7                       1.555556
2.8                       1.707143
2.9                       1.320000
3.0                       1.403846
3.1                       1.245455
3.2                       1.261538
3.3                       1.566667
3.4                       0.716667
3.5                       0.300000
3.6                       0.750000
3.7                       0.266667
3.8                       0.900000
3.9                       0.400000
4.0                       0.200000
4.1                       0.100000
4.2                       0.200000
4.4                       0.400000

In [39]:
df.groupby(df.columns[1]).apply(my_mean,result_type='broadcast')

TypeError: my_mean() got an unexpected keyword argument 'result_type'

In [16]:
#df.groupby(df.columns[1])
print(df.groupby(df.columns[1]).transform(add))

----
Passed in -- <class 'pandas.core.series.Series'>
60    5.0
Name: sepal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
60    3.5
Name: petal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
60    1.0
Name: petal width (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
60                5.0                3.5               1.0
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
62     6.0
68     6.2
119    6.0
Name: sepal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
62     4.0
68     4.5
119    5.0
Name: petal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
62     1.0
68     1.5
119    1.5
Name: petal width (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
62                 6.0                4.0               1.0
68                 6.2                4.5               1.5
119                6.0                5.0               1.5
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
41    4.5
53    5.5
87    6.3
93    5.0
Name: sepal length (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
41    1.3
53    4.0
87    4.4
93    3.3
Name: petal length (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
41    0.3
53    1.3
87    1.3
93    1.0
Name: petal width (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
41                4.5                1.3               0.3
53                5.5                4.0               1.3
87                6.3                4.4               1.3
93                5.0                3.3               1.0
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
57    4.9
80    5.5
81    5.5
Name: sepal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
57    3.3
80    3.8
81    3.7
Name: petal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
57    1.0
80    1.1
81    1.0
Name: petal width (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
57                4.9                3.3               1.0
80                5.5                3.8               1.1
81                5.5                3.7               1.0
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
69     5.6
72     6.3
89     5.5
98     5.1
106    4.9
108    6.7
113    5.7
146    6.3
Name: sepal length (cm), dtype: float64
Passed in length 8 return length 8
----
----
Passed in -- <class 'pandas.core.series.Series'>
69     3.9
72     4.9
89     4.0
98     3.0
106    4.5
108    5.8
113    5.0
146    5.0
Name: petal length (cm), dtype: float64
Passed in length 8 return length 8
----
----
Passed in -- <class 'pandas.core.series.Series'>
69     1.1
72     1.5
89     1.3
98     1.1
106    1.7
108    1.8
113    2.0
146    1.9
Name: petal width (cm), dtype: float64
Passed in length 8 return length 8
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
69                 5.6                3.9               1.1
72                 6.3                4.9               1.5
89                 5.5                4.0               1.3
98                 5.1                3.0               1.1
106                4.9                4.5               1.7
108                6.7                5.8               1.8
113                5.7                5.0               2.0
146                6.3                5.0               1.9
Passed in length 8 return length 8
----
----
Passed in -- <class 'pandas.core.series.Series'>
79     5.7
90     5.5
92     5.8
118    7.7
134    6.1
Name: sepal length (cm), dtype: float64
Passed in length 5 return length 5
----
----
Passed in -- <class 'pandas.core.series.Series'>
79     3.5
90     4.4
92     4.0
118    6.9
134    5.6
Name: petal length (cm), dtype: float64
Passed in length 5 return length 5
----
----
Passed in -- <class 'pandas.core.series.Series'>
79     1.0
90     1.2
92     1.2
118    2.3
134    1.4
Name: petal width (cm), dtype: float64
Passed in length 5 return length 5
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
79                 5.7                3.5               1.0
90                 5.5                4.4               1.2
92                 5.8                4.0               1.2
118                7.7                6.9               2.3
134                6.1                5.6               1.4
Passed in length 5 return length 5
----
----
Passed in -- <class 'pandas.core.series.Series'>
59     5.2
67     5.8
82     5.8
83     6.0
94     5.6
101    5.8
111    6.4
123    6.3
142    5.8
Name: sepal length (cm), dtype: float64
Passed in length 9 return length 9
----
----
Passed in -- <class 'pandas.core.series.Series'>
59     3.9
67     4.1
82     3.9
83     5.1
94     4.2
101    5.1
111    5.3
123    4.9
142    5.1
Name: petal length (cm), dtype: float64
Passed in length 9 return length 9
----
----
Passed in -- <class 'pandas.core.series.Series'>
59     1.4
67     1.0
82     1.2
83     1.6
94     1.3
101    1.9
111    1.9
123    1.8
142    1.9
Name: petal width (cm), dtype: float64
Passed in length 9 return length 9
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
59                 5.2                3.9               1.4
67                 5.8                4.1               1.0
82                 5.8                3.9               1.2
83                 6.0                5.1               1.6
94                 5.6                4.2               1.3
101                5.8                5.1               1.9
111                6.4                5.3               1.9
123                6.3                4.9               1.8
142                5.8                5.1               1.9
Passed in length 9 return length 9
----
----
Passed in -- <class 'pandas.core.series.Series'>
54     6.5
55     5.7
71     6.1
73     6.1
76     6.8
99     5.7
114    5.8
121    5.6
122    7.7
126    6.2
128    6.4
130    7.4
132    6.4
133    6.3
Name: sepal length (cm), dtype: float64
Passed in length 14 return length 14
----
----
Passed in -- <class 'pandas.core.series.Series'>
54     4.6
55     4.5
71     4.0
73     4.7
76     4.8
99     4.1
114    5.1
121    4.9
122    6.7
126    4.8
128    5.6
130    6.1
132    5.6
133    5.1
Name: petal length (cm), dtype: float64
Passed in length 14 return length 14
----
----
Passed in -- <class 'pandas.core.series.Series'>
54     1.5
55     1.3
71     1.3
73     1.2
76     1.4
99     1.3
114    2.4
121    2.0
122    2.0
126    1.8
128    2.1
130    1.9
132    2.2
133    1.5
Name: petal width (cm), dtype: float64
Passed in length 14 return length 14
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
54                 6.5                4.6               1.5
55                 5.7                4.5               1.3
71                 6.1                4.0               1.3
73                 6.1                4.7               1.2
76                 6.8                4.8               1.4
99                 5.7                4.1               1.3
114                5.8                5.1               2.4
121                5.6                4.9               2.0
122                7.7                6.7               2.0
126                6.2                4.8               1.8
128                6.4                5.6               2.1
130                7.4                6.1               1.9
132                6.4                5.6               2.2
133                6.3                5.1               1.5
Passed in length 14 return length 14
----
----
Passed in -- <class 'pandas.core.series.Series'>
8      4.4
58     6.6
63     6.1
64     5.6
74     6.4
78     6.0
96     5.7
97     6.2
103    6.3
107    7.3
Name: sepal length (cm), dtype: float64
Passed in length 10 return length 10
----
----
Passed in -- <class 'pandas.core.series.Series'>
8      1.4
58     4.6
63     4.7
64     3.6
74     4.3
78     4.5
96     4.2
97     4.3
103    5.6
107    6.3
Name: petal length (cm), dtype: float64
Passed in length 10 return length 10
----
----
Passed in -- <class 'pandas.core.series.Series'>
8      0.2
58     1.3
63     1.4
64     1.3
74     1.3
78     1.5
96     1.3
97     1.3
103    1.8
107    1.8
Name: petal width (cm), dtype: float64
Passed in length 10 return length 10
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
8                  4.4                1.4               0.2
58                 6.6                4.6               1.3
63                 6.1                4.7               1.4
64                 5.6                3.6               1.3
74                 6.4                4.3               1.3
78                 6.0                4.5               1.5
96                 5.7                4.2               1.3
97                 6.2                4.3               1.3
103                6.3                5.6               1.8
107                7.3                6.3               1.8
Passed in length 10 return length 10
----
----
Passed in -- <class 'pandas.core.series.Series'>
1      4.9
12     4.8
13     4.3
25     5.0
38     4.4
45     4.8
61     5.9
66     5.6
75     6.6
77     6.7
84     5.4
88     5.6
91     6.1
95     5.7
102    7.1
104    6.5
105    7.6
112    6.8
116    6.5
127    6.1
129    7.2
135    7.7
138    6.0
145    6.7
147    6.5
149    5.9
Name: sepal length (cm), dtype: float64
Passed in length 26 return length 26
----
----
Passed in -- <class 'pandas.core.series.Series'>
1      1.4
12     1.4
13     1.1
25     1.6
38     1.3
45     1.4
61     4.2
66     4.5
75     4.4
77     5.0
84     4.5
88     4.1
91     4.6
95     4.2
102    5.9
104    5.8
105    6.6
112    5.5
116    5.5
127    4.9
129    5.8
135    6.1
138    4.8
145    5.2
147    5.2
149    5.1
Name: petal length (cm), dtype: float64
Passed in length 26 return length 26
----
----
Passed in -- <class 'pandas.core.series.Series'>
1      0.2
12     0.1
13     0.1
25     0.2
38     0.2
45     0.3
61     1.5
66     1.5
75     1.4
77     1.7
84     1.5
88     1.3
91     1.4
95     1.2
102    2.1
104    2.2
105    2.1
112    2.1
116    1.8
127    1.8
129    1.6
135    2.3
138    1.8
145    2.3
147    2.0
149    1.8
Name: petal width (cm), dtype: float64
Passed in length 26 return length 26
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
1                  4.9                1.4               0.2
12                 4.8                1.4               0.1
13                 4.3                1.1               0.1
25                 5.0                1.6               0.2
38                 4.4                1.3               0.2
45                 4.8                1.4               0.3
61                 5.9                4.2               1.5
66                 5.6                4.5               1.5
75                 6.6                4.4               1.4
77                 6.7                5.0               1.7
84                 5.4                4.5               1.5
88                 5.6                4.1               1.3
91                 6.1                4.6               1.4
95                 5.7                4.2               1.2
102                7.1                5.9               2.1
104                6.5                5.8               2.2
105                7.6                6.6               2.1
112                6.8                5.5               2.1
116                6.5                5.5               1.8
127                6.1                4.9               1.8
129                7.2                5.8               1.6
135                7.7                6.1               2.3
138                6.0                4.8               1.8
145                6.7                5.2               2.3
147                6.5                5.2               2.0
149                5.9                5.1               1.8
Passed in length 26 return length 26
----
----
Passed in -- <class 'pandas.core.series.Series'>
3      4.6
9      4.9
30     4.8
34     4.9
52     6.9
65     6.7
86     6.7
137    6.4
139    6.9
140    6.7
141    6.9
Name: sepal length (cm), dtype: float64
Passed in length 11 return length 11
----
----
Passed in -- <class 'pandas.core.series.Series'>
3      1.5
9      1.5
30     1.6
34     1.5
52     4.9
65     4.4
86     4.7
137    5.5
139    5.4
140    5.6
141    5.1
Name: petal length (cm), dtype: float64
Passed in length 11 return length 11
----
----
Passed in -- <class 'pandas.core.series.Series'>
3      0.2
9      0.1
30     0.2
34     0.2
52     1.5
65     1.4
86     1.5
137    1.8
139    2.1
140    2.4
141    2.3
Name: petal width (cm), dtype: float64
Passed in length 11 return length 11
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
3                  4.6                1.5               0.2
9                  4.9                1.5               0.1
30                 4.8                1.6               0.2
34                 4.9                1.5               0.2
52                 6.9                4.9               1.5
65                 6.7                4.4               1.4
86                 6.7                4.7               1.5
137                6.4                5.5               1.8
139                6.9                5.4               2.1
140                6.7                5.6               2.4

141                6.9                5.1               2.3
Passed in length 11 return length 11
----
----
Passed in -- <class 'pandas.core.series.Series'>
2      4.7
29     4.7
35     5.0
42     4.4
47     4.6
50     7.0
51     6.4
70     5.9
110    6.5
115    6.4
120    6.9
125    7.2
143    6.8
Name: sepal length (cm), dtype: float64
Passed in length 13 return length 13
----
----
Passed in -- <class 'pandas.core.series.Series'>
2      1.3
29     1.6
35     1.2
42     1.3
47     1.4
50     4.7
51     4.5
70     4.8
110    5.1
115    5.3
120    5.7
125    6.0
143    5.9
Name: petal length (cm), dtype: float64
Passed in length 13 return length 13
----
----
Passed in -- <class 'pandas.core.series.Series'>
2      0.2
29     0.2
35     0.2
42     0.2
47     0.2
50     1.4
51     1.5
70     1.8
110    2.0
115    2.3
120    2.3
125    1.8
143    2.3
Name: petal width (cm), dtype: float64
Passed in length 13 return length 13
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
2                  4.7                1.3               0.2
29                 4.7                1.6               0.2
35                 5.0                1.2               0.2
42                 4.4                1.3               0.2
47                 4.6                1.4               0.2
50                 7.0                4.7               1.4
51                 6.4                4.5               1.5
70                 5.9                4.8               1.8
110                6.5                5.1               2.0
115                6.4                5.3               2.3
120                6.9                5.7               2.3
125                7.2                6.0               1.8
143                6.8                5.9               2.3
Passed in length 13 return length 13
----
----
Passed in -- <class 'pandas.core.series.Series'>
23     5.1
49     5.0
56     6.3
100    6.3
124    6.7
144    6.7
Name: sepal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
23     1.7
49     1.4
56     4.7
100    6.0
124    5.7
144    5.7
Name: petal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
23     0.5
49     0.2
56     1.6
100    2.5
124    2.1
144    2.5
Name: petal width (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
23                 5.1                1.7               0.5
49                 5.0                1.4               0.2
56                 6.3                4.7               1.6
100                6.3                6.0               2.5
124                6.7                5.7               2.1
144                6.7                5.7               2.5
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
6      4.6
7      5.0
11     4.8
20     5.4
24     4.8
26     5.0
28     5.2
31     5.4
39     5.1
85     6.0
136    6.3
148    6.2
Name: sepal length (cm), dtype: float64
Passed in length 12 return length 12
----
----
Passed in -- <class 'pandas.core.series.Series'>
6      1.4
7      1.5
11     1.6
20     1.7
24     1.9
26     1.6
28     1.4
31     1.5
39     1.5
85     4.5
136    5.6
148    5.4
Name: petal length (cm), dtype: float64
Passed in length 12 return length 12
----
----
Passed in -- <class 'pandas.core.series.Series'>
6      0.3
7      0.2
11     0.2
20     0.2
24     0.2
26     0.4
28     0.2
31     0.4
39     0.2
85     1.6
136    2.4
148    2.3
Name: petal width (cm), dtype: float64
Passed in length 12 return length 12
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
6                  4.6                1.4               0.3
7                  5.0                1.5               0.2
11                 4.8                1.6               0.2
20                 5.4                1.7               0.2
24                 4.8                1.9               0.2
26                 5.0                1.6               0.4
28                 5.2                1.4               0.2
31                 5.4                1.5               0.4
39                 5.1                1.5               0.2
85                 6.0                4.5               1.6
136                6.3                5.6               2.4
148                6.2                5.4               2.3
Passed in length 12 return length 12
----
----
Passed in -- <class 'pandas.core.series.Series'>
0     5.1
17    5.1
27    5.2
36    5.5
40    5.0
43    5.0
Name: sepal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
0     1.4
17    1.4
27    1.5
36    1.3
40    1.3
43    1.6
Name: petal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
0     0.2
17    0.3
27    0.2
36    0.2
40    0.3
43    0.6
Name: petal width (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
0                 5.1                1.4               0.2
17                5.1                1.4               0.3
27                5.2                1.5               0.2
36                5.5                1.3               0.2
40                5.0                1.3               0.3
43                5.0                1.6               0.6
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
4      5.0
22     4.6
37     4.9
109    7.2
Name: sepal length (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
4      1.4
22     1.0
37     1.4
109    6.1
Name: petal length (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
4      0.2
22     0.2
37     0.1
109    2.5
Name: petal width (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
4                  5.0                1.4               0.2
22                 4.6                1.0               0.2
37                 4.9                1.4               0.1
109                7.2                6.1               2.5
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
10    5.4
21    5.1
48    5.3
Name: sepal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
10    1.5
21    1.5
48    1.5
Name: petal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
10    0.2
21    0.4
48    0.2
Name: petal width (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
10                5.4                1.5               0.2
21                5.1                1.5               0.4
48                5.3                1.5               0.2
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
18     5.7
19     5.1
44     5.1
46     5.1
117    7.7
131    7.9
Name: sepal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
18     1.7
19     1.5
44     1.9
46     1.6
117    6.7
131    6.4
Name: petal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
18     0.3
19     0.3
44     0.4
46     0.2
117    2.2
131    2.0
Name: petal width (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
18                 5.7                1.7               0.3
19                 5.1                1.5               0.3
44                 5.1                1.9               0.4
46                 5.1                1.6               0.2
117                7.7                6.7               2.2

131                7.9                6.4               2.0
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
5     5.4
16    5.4
Name: sepal length (cm), dtype: float64
Passed in length 2 return length 2
----
----
Passed in -- <class 'pandas.core.series.Series'>
5     1.7
16    1.3
Name: petal length (cm), dtype: float64
Passed in length 2 return length 2
----
----
Passed in -- <class 'pandas.core.series.Series'>
5     0.4
16    0.4
Name: petal width (cm), dtype: float64
Passed in length 2 return length 2
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
5                 5.4                1.7               0.4
16                5.4                1.3               0.4
Passed in length 2 return length 2
----
----
Passed in -- <class 'pandas.core.series.Series'>
14    5.8
Name: sepal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
14    1.2
Name: petal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
14    0.2
Name: petal width (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
14                5.8                1.2               0.2
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
32    5.2
Name: sepal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
32    1.5
Name: petal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
32    0.1
Name: petal width (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
32                5.2                1.5               0.1
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
33    5.5
Name: sepal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
33    1.4
Name: petal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
33    0.2
Name: petal width (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
33                5.5                1.4               0.2
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
15    5.7
Name: sepal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
15    1.5
Name: petal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
15    0.4
Name: petal width (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
15                5.7                1.5               0.4
Passed in length 1 return length 1
----
     sepal length (cm)  petal length (cm)  petal width (cm)
0                 15.1               11.4              10.2
1                 14.9               11.4              10.2
2                 14.7               11.3              10.2
3                 14.6               11.5              10.2
4                 15.0               11.4              10.2
..                 ...                ...               ...
145               16.7               15.2              12.3
146               16.3               15.0              11.9
147               16.5               15.2              12.0
148               16.2               15.4              12.3
149               15.9               15.1              11.8

[150 rows x 3 columns]

In [35]:
t_groupby=df.groupby(df.columns[1]).transform(my_mean)
print(t_groupby)
print(t_groupby.loc[[62,68,119]])

----
Passed in -- <class 'pandas.core.series.Series'>
60    5.0
Name: sepal length (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 5.0
----
----
Passed in -- <class 'pandas.core.series.Series'>
60    3.5
Name: petal length (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 3.5
----
----
Passed in -- <class 'pandas.core.series.Series'>
60    1.0
Name: petal width (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 1.0
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
60                5.0                3.5               1.0
passed in length 1 return length =1 scalar (3,)
return value sepal length (cm)    5.0
petal length (cm)    3.5
petal width (cm)     1.0
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
62     6.0
68     6.2
119    6.0
Name: sepal length (cm), dtype: float64
passed in length 3 return length =1 scalar ()
return value 6.066666666666666
----
----
Passed in -- <class 'pandas.core.series.Series'>
62     4.0
68     4.5
119    5.0
Name: petal length (cm), dtype: float64
passed in length 3 return length =1 scalar ()
return value 4.5
----
----
Passed in -- <class 'pandas.core.series.Series'>
62     1.0
68     1.5
119    1.5
Name: petal width (cm), dtype: float64
passed in length 3 return length =1 scalar ()
return value 1.3333333333333333
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
62                 6.0                4.0               1.0
68                 6.2                4.5               1.5
119                6.0                5.0               1.5
passed in length 3 return length =1 scalar (3,)
return value sepal length (cm)    6.066667
petal length (cm)    4.500000
petal width (cm)     1.333333
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
41    4.5
53    5.5
87    6.3
93    5.0
Name: sepal length (cm), dtype: float64
passed in length 4 return length =1 scalar ()
return value 5.325
----
----
Passed in -- <class 'pandas.core.series.Series'>
41    1.3
53    4.0
87    4.4
93    3.3
Name: petal length (cm), dtype: float64
passed in length 4 return length =1 scalar ()
return value 3.25
----
----
Passed in -- <class 'pandas.core.series.Series'>
41    0.3
53    1.3
87    1.3
93    1.0
Name: petal width (cm), dtype: float64
passed in length 4 return length =1 scalar ()
return value 0.9750000000000001
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
41                4.5                1.3               0.3
53                5.5                4.0               1.3
87                6.3                4.4               1.3
93                5.0                3.3               1.0
passed in length 4 return length =1 scalar (3,)
return value sepal length (cm)    5.325
petal length (cm)    3.250
petal width (cm)     0.975
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
57    4.9
80    5.5
81    5.5
Name: sepal length (cm), dtype: float64
passed in length 3 return length =1 scalar ()
return value 5.3
----
----
Passed in -- <class 'pandas.core.series.Series'>
57    3.3
80    3.8
81    3.7
Name: petal length (cm), dtype: float64
passed in length 3 return length =1 scalar ()
return value 3.6
----
----
Passed in -- <class 'pandas.core.series.Series'>
57    1.0
80    1.1
81    1.0
Name: petal width (cm), dtype: float64
passed in length 3 return length =1 scalar ()
return value 1.0333333333333334
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
57                4.9                3.3               1.0
80                5.5                3.8               1.1
81                5.5                3.7               1.0
passed in length 3 return length =1 scalar (3,)
return value sepal length (cm)    5.300000
petal length (cm)    3.600000
petal width (cm)     1.033333
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
69     5.6
72     6.3
89     5.5
98     5.1
106    4.9
108    6.7
113    5.7
146    6.3
Name: sepal length (cm), dtype: float64
passed in length 8 return length =1 scalar ()
return value 5.7625
----
----
Passed in -- <class 'pandas.core.series.Series'>
69     3.9
72     4.9
89     4.0
98     3.0
106    4.5
108    5.8
113    5.0
146    5.0
Name: petal length (cm), dtype: float64
passed in length 8 return length =1 scalar ()
return value 4.5125
----
----
Passed in -- <class 'pandas.core.series.Series'>
69     1.1
72     1.5
89     1.3
98     1.1
106    1.7
108    1.8
113    2.0
146    1.9
Name: petal width (cm), dtype: float64
passed in length 8 return length =1 scalar ()
return value 1.55
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
69                 5.6                3.9               1.1
72                 6.3                4.9               1.5
89                 5.5                4.0               1.3
98                 5.1                3.0               1.1
106                4.9                4.5               1.7
108                6.7                5.8               1.8
113                5.7                5.0               2.0
146                6.3                5.0               1.9
passed in length 8 return length =1 scalar (3,)
return value sepal length (cm)    5.7625
petal length (cm)    4.5125
petal width (cm)     1.5500
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
79     5.7
90     5.5
92     5.8
118    7.7
134    6.1
Name: sepal length (cm), dtype: float64
passed in length 5 return length =1 scalar ()
return value 6.159999999999999
----
----
Passed in -- <class 'pandas.core.series.Series'>
79     3.5
90     4.4
92     4.0
118    6.9
134    5.6
Name: petal length (cm), dtype: float64
passed in length 5 return length =1 scalar ()
return value 4.88
----
----
Passed in -- <class 'pandas.core.series.Series'>
79     1.0
90     1.2
92     1.2
118    2.3
134    1.4
Name: petal width (cm), dtype: float64
passed in length 5 return length =1 scalar ()
return value 1.42
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
79                 5.7                3.5               1.0
90                 5.5                4.4               1.2
92                 5.8                4.0               1.2
118                7.7                6.9               2.3
134                6.1                5.6               1.4
passed in length 5 return length =1 scalar (3,)
return value sepal length (cm)    6.16
petal length (cm)    4.88
petal width (cm)     1.42
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
59     5.2
67     5.8
82     5.8
83     6.0
94     5.6
101    5.8
111    6.4
123    6.3
142    5.8
Name: sepal length (cm), dtype: float64
passed in length 9 return length =1 scalar ()
return value 5.855555555555555
----
----
Passed in -- <class 'pandas.core.series.Series'>
59     3.9
67     4.1
82     3.9
83     5.1
94     4.2
101    5.1
111    5.3
123    4.9
142    5.1
Name: petal length (cm), dtype: float64
passed in length 9 return length =1 scalar ()
return value 4.622222222222223
----
----
Passed in -- <class 'pandas.core.series.Series'>
59     1.4
67     1.0
82     1.2
83     1.6
94     1.3
101    1.9
111    1.9
123    1.8
142    1.9
Name: petal width (cm), dtype: float64
passed in length 9 return length =1 scalar ()
return value 1.5555555555555556
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
59                 5.2                3.9               1.4
67                 5.8                4.1               1.0
82                 5.8                3.9               1.2
83                 6.0                5.1               1.6
94                 5.6                4.2               1.3
101                5.8                5.1               1.9
111                6.4                5.3               1.9
123                6.3                4.9               1.8
142                5.8                5.1               1.9
passed in length 9 return length =1 scalar (3,)
return value sepal length (cm)    5.855556
petal length (cm)    4.622222
petal width (cm)     1.555556
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
54     6.5
55     5.7
71     6.1
73     6.1
76     6.8
99     5.7
114    5.8
121    5.6
122    7.7
126    6.2
128    6.4
130    7.4
132    6.4
133    6.3
Name: sepal length (cm), dtype: float64
passed in length 14 return length =1 scalar ()
return value 6.335714285714287
----
----
Passed in -- <class 'pandas.core.series.Series'>
54     4.6
55     4.5
71     4.0
73     4.7
76     4.8
99     4.1
114    5.1
121    4.9
122    6.7
126    4.8
128    5.6
130    6.1
132    5.6
133    5.1
Name: petal length (cm), dtype: float64
passed in length 14 return length =1 scalar ()
return value 5.042857142857143
----
----
Passed in -- <class 'pandas.core.series.Series'>
54     1.5
55     1.3
71     1.3
73     1.2
76     1.4
99     1.3
114    2.4
121    2.0
122    2.0
126    1.8
128    2.1
130    1.9
132    2.2
133    1.5
Name: petal width (cm), dtype: float64
passed in length 14 return length =1 scalar ()
return value 1.707142857142857
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
54                 6.5                4.6               1.5
55                 5.7                4.5               1.3
71                 6.1                4.0               1.3
73                 6.1                4.7               1.2
76                 6.8                4.8               1.4
99                 5.7                4.1               1.3
114                5.8                5.1               2.4
121                5.6                4.9               2.0
122                7.7                6.7               2.0
126                6.2                4.8               1.8
128                6.4                5.6               2.1
130                7.4                6.1               1.9
132                6.4                5.6               2.2
133                6.3                5.1               1.5
passed in length 14 return length =1 scalar (3,)
return value sepal length (cm)    6.335714
petal length (cm)    5.042857
petal width (cm)     1.707143
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
8      4.4
58     6.6
63     6.1
64     5.6
74     6.4
78     6.0
96     5.7
97     6.2
103    6.3
107    7.3

Name: sepal length (cm), dtype: float64
passed in length 10 return length =1 scalar ()
return value 6.06
----
----
Passed in -- <class 'pandas.core.series.Series'>
8      1.4
58     4.6
63     4.7
64     3.6
74     4.3
78     4.5
96     4.2
97     4.3
103    5.6
107    6.3
Name: petal length (cm), dtype: float64
passed in length 10 return length =1 scalar ()
return value 4.35
----
----
Passed in -- <class 'pandas.core.series.Series'>
8      0.2
58     1.3
63     1.4
64     1.3
74     1.3
78     1.5
96     1.3
97     1.3
103    1.8
107    1.8
Name: petal width (cm), dtype: float64
passed in length 10 return length =1 scalar ()
return value 1.3200000000000003
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
8                  4.4                1.4               0.2
58                 6.6                4.6               1.3
63                 6.1                4.7               1.4
64                 5.6                3.6               1.3
74                 6.4                4.3               1.3
78                 6.0                4.5               1.5
96                 5.7                4.2               1.3
97                 6.2                4.3               1.3
103                6.3                5.6               1.8
107                7.3                6.3               1.8
passed in length 10 return length =1 scalar (3,)
return value sepal length (cm)    6.06
petal length (cm)    4.35
petal width (cm)     1.32
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
1      4.9
12     4.8
13     4.3
25     5.0
38     4.4
45     4.8
61     5.9
66     5.6
75     6.6
77     6.7
84     5.4
88     5.6
91     6.1
95     5.7
102    7.1
104    6.5
105    7.6
112    6.8
116    6.5
127    6.1
129    7.2
135    7.7
138    6.0
145    6.7
147    6.5
149    5.9
Name: sepal length (cm), dtype: float64
passed in length 26 return length =1 scalar ()
return value 6.015384615384615
----
----
Passed in -- <class 'pandas.core.series.Series'>
1      1.4
12     1.4
13     1.1
25     1.6
38     1.3
45     1.4
61     4.2
66     4.5
75     4.4
77     5.0
84     4.5
88     4.1
91     4.6
95     4.2
102    5.9
104    5.8
105    6.6
112    5.5
116    5.5
127    4.9
129    5.8
135    6.1
138    4.8
145    5.2
147    5.2
149    5.1
Name: petal length (cm), dtype: float64
passed in length 26 return length =1 scalar ()
return value 4.234615384615385
----
----
Passed in -- <class 'pandas.core.series.Series'>
1      0.2
12     0.1
13     0.1
25     0.2
38     0.2
45     0.3
61     1.5
66     1.5
75     1.4
77     1.7
84     1.5
88     1.3
91     1.4
95     1.2
102    2.1
104    2.2
105    2.1
112    2.1
116    1.8
127    1.8
129    1.6
135    2.3
138    1.8
145    2.3
147    2.0
149    1.8
Name: petal width (cm), dtype: float64
passed in length 26 return length =1 scalar ()
return value 1.4038461538461537
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
1                  4.9                1.4               0.2
12                 4.8                1.4               0.1
13                 4.3                1.1               0.1
25                 5.0                1.6               0.2
38                 4.4                1.3               0.2
45                 4.8                1.4               0.3
61                 5.9                4.2               1.5
66                 5.6                4.5               1.5
75                 6.6                4.4               1.4
77                 6.7                5.0               1.7
84                 5.4                4.5               1.5
88                 5.6                4.1               1.3
91                 6.1                4.6               1.4
95                 5.7                4.2               1.2
102                7.1                5.9               2.1
104                6.5                5.8               2.2
105                7.6                6.6               2.1
112                6.8                5.5               2.1
116                6.5                5.5               1.8
127                6.1                4.9               1.8
129                7.2                5.8               1.6
135                7.7                6.1               2.3
138                6.0                4.8               1.8
145                6.7                5.2               2.3
147                6.5                5.2               2.0
149                5.9                5.1               1.8
passed in length 26 return length =1 scalar (3,)
return value sepal length (cm)    6.015385
petal length (cm)    4.234615
petal width (cm)     1.403846
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
3      4.6
9      4.9
30     4.8
34     4.9
52     6.9
65     6.7
86     6.7
137    6.4
139    6.9
140    6.7
141    6.9
Name: sepal length (cm), dtype: float64
passed in length 11 return length =1 scalar ()
return value 6.036363636363637
----
----
Passed in -- <class 'pandas.core.series.Series'>
3      1.5
9      1.5
30     1.6
34     1.5
52     4.9
65     4.4
86     4.7
137    5.5
139    5.4
140    5.6
141    5.1
Name: petal length (cm), dtype: float64
passed in length 11 return length =1 scalar ()
return value 3.790909090909091
----
----
Passed in -- <class 'pandas.core.series.Series'>
3      0.2
9      0.1
30     0.2
34     0.2
52     1.5
65     1.4
86     1.5
137    1.8
139    2.1
140    2.4
141    2.3
Name: petal width (cm), dtype: float64
passed in length 11 return length =1 scalar ()
return value 1.2454545454545454
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
3                  4.6                1.5               0.2
9                  4.9                1.5               0.1
30                 4.8                1.6               0.2
34                 4.9                1.5               0.2
52                 6.9                4.9               1.5
65                 6.7                4.4               1.4
86                 6.7                4.7               1.5
137                6.4                5.5               1.8
139                6.9                5.4               2.1
140                6.7                5.6               2.4
141                6.9                5.1               2.3
passed in length 11 return length =1 scalar (3,)
return value sepal length (cm)    6.036364
petal length (cm)    3.790909
petal width (cm)     1.245455
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
2      4.7
29     4.7
35     5.0
42     4.4
47     4.6
50     7.0
51     6.4
70     5.9
110    6.5
115    6.4
120    6.9
125    7.2
143    6.8
Name: sepal length (cm), dtype: float64
passed in length 13 return length =1 scalar ()
return value 5.884615384615385
----
----
Passed in -- <class 'pandas.core.series.Series'>
2      1.3
29     1.6
35     1.2
42     1.3
47     1.4
50     4.7
51     4.5
70     4.8
110    5.1
115    5.3
120    5.7
125    6.0
143    5.9
Name: petal length (cm), dtype: float64
passed in length 13 return length =1 scalar ()
return value 3.753846153846154
----
----
Passed in -- <class 'pandas.core.series.Series'>
2      0.2
29     0.2
35     0.2
42     0.2
47     0.2
50     1.4
51     1.5
70     1.8
110    2.0
115    2.3
120    2.3
125    1.8
143    2.3
Name: petal width (cm), dtype: float64
passed in length 13 return length =1 scalar ()
return value 1.2615384615384617
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
2                  4.7                1.3               0.2
29                 4.7                1.6               0.2
35                 5.0                1.2               0.2
42                 4.4                1.3               0.2
47                 4.6                1.4               0.2
50                 7.0                4.7               1.4
51                 6.4                4.5               1.5
70                 5.9                4.8               1.8
110                6.5                5.1               2.0
115                6.4                5.3               2.3
120                6.9                5.7               2.3
125                7.2                6.0               1.8
143                6.8                5.9               2.3
passed in length 13 return length =1 scalar (3,)
return value sepal length (cm)    5.884615
petal length (cm)    3.753846
petal width (cm)     1.261538
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
23     5.1
49     5.0
56     6.3
100    6.3
124    6.7
144    6.7
Name: sepal length (cm), dtype: float64
passed in length 6 return length =1 scalar ()
return value 6.016666666666667
----
----
Passed in -- <class 'pandas.core.series.Series'>
23     1.7
49     1.4
56     4.7
100    6.0
124    5.7
144    5.7
Name: petal length (cm), dtype: float64
passed in length 6 return length =1 scalar ()
return value 4.2
----
----
Passed in -- <class 'pandas.core.series.Series'>
23     0.5
49     0.2
56     1.6
100    2.5
124    2.1
144    2.5
Name: petal width (cm), dtype: float64
passed in length 6 return length =1 scalar ()
return value 1.5666666666666667
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
23                 5.1                1.7               0.5
49                 5.0                1.4               0.2
56                 6.3                4.7               1.6
100                6.3                6.0               2.5
124                6.7                5.7               2.1
144                6.7                5.7               2.5
passed in length 6 return length =1 scalar (3,)
return value sepal length (cm)    6.016667
petal length (cm)    4.200000
petal width (cm)     1.566667
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
6      4.6
7      5.0
11     4.8
20     5.4
24     4.8
26     5.0
28     5.2
31     5.4
39     5.1
85     6.0
136    6.3
148    6.2
Name: sepal length (cm), dtype: float64
passed in length 12 return length =1 scalar ()
return value 5.316666666666667
----
----
Passed in -- <class 'pandas.core.series.Series'>
6      1.4
7      1.5
11     1.6
20     1.7
24     1.9
26     1.6
28     1.4
31     1.5
39     1.5
85     4.5
136    5.6
148    5.4
Name: petal length (cm), dtype: float64
passed in length 12 return length =1 scalar ()
return value 2.466666666666667
----
----
Passed in -- <class 'pandas.core.series.Series'>
6      0.3
7      0.2
11     0.2
20     0.2
24     0.2
26     0.4
28     0.2
31     0.4
39     0.2
85     1.6
136    2.4
148    2.3
Name: petal width (cm), dtype: float64
passed in length 12 return length =1 scalar ()
return value 0.7166666666666668
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
6                  4.6                1.4               0.3
7                  5.0                1.5               0.2
11                 4.8                1.6               0.2
20                 5.4                1.7               0.2
24                 4.8                1.9               0.2
26                 5.0                1.6               0.4
28                 5.2                1.4               0.2
31                 5.4                1.5               0.4
39                 5.1                1.5               0.2
85                 6.0                4.5               1.6
136                6.3                5.6               2.4
148                6.2                5.4               2.3
passed in length 12 return length =1 scalar (3,)
return value sepal length (cm)    5.316667
petal length (cm)    2.466667
petal width (cm)     0.716667
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
0     5.1
17    5.1
27    5.2
36    5.5
40    5.0
43    5.0
Name: sepal length (cm), dtype: float64
passed in length 6 return length =1 scalar ()
return value 5.1499999999999995
----
----
Passed in -- <class 'pandas.core.series.Series'>
0     1.4
17    1.4
27    1.5
36    1.3
40    1.3
43    1.6
Name: petal length (cm), dtype: float64
passed in length 6 return length =1 scalar ()
return value 1.4166666666666667
----
----
Passed in -- <class 'pandas.core.series.Series'>
0     0.2
17    0.3
27    0.2
36    0.2
40    0.3
43    0.6
Name: petal width (cm), dtype: float64
passed in length 6 return length =1 scalar ()
return value 0.3
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
0                 5.1                1.4               0.2
17                5.1                1.4               0.3
27                5.2                1.5               0.2
36                5.5                1.3               0.2
40                5.0                1.3               0.3

43                5.0                1.6               0.6
passed in length 6 return length =1 scalar (3,)
return value sepal length (cm)    5.150000
petal length (cm)    1.416667
petal width (cm)     0.300000
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
4      5.0
22     4.6
37     4.9
109    7.2
Name: sepal length (cm), dtype: float64
passed in length 4 return length =1 scalar ()
return value 5.425
----
----
Passed in -- <class 'pandas.core.series.Series'>
4      1.4
22     1.0
37     1.4
109    6.1
Name: petal length (cm), dtype: float64
passed in length 4 return length =1 scalar ()
return value 2.4749999999999996
----
----
Passed in -- <class 'pandas.core.series.Series'>
4      0.2
22     0.2
37     0.1
109    2.5
Name: petal width (cm), dtype: float64
passed in length 4 return length =1 scalar ()
return value 0.75
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
4                  5.0                1.4               0.2
22                 4.6                1.0               0.2
37                 4.9                1.4               0.1
109                7.2                6.1               2.5
passed in length 4 return length =1 scalar (3,)
return value sepal length (cm)    5.425
petal length (cm)    2.475
petal width (cm)     0.750
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
10    5.4
21    5.1
48    5.3
Name: sepal length (cm), dtype: float64
passed in length 3 return length =1 scalar ()
return value 5.266666666666667
----
----
Passed in -- <class 'pandas.core.series.Series'>
10    1.5
21    1.5
48    1.5
Name: petal length (cm), dtype: float64
passed in length 3 return length =1 scalar ()
return value 1.5
----
----
Passed in -- <class 'pandas.core.series.Series'>
10    0.2
21    0.4
48    0.2
Name: petal width (cm), dtype: float64
passed in length 3 return length =1 scalar ()
return value 0.26666666666666666
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
10                5.4                1.5               0.2
21                5.1                1.5               0.4
48                5.3                1.5               0.2
passed in length 3 return length =1 scalar (3,)
return value sepal length (cm)    5.266667
petal length (cm)    1.500000
petal width (cm)     0.266667
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
18     5.7
19     5.1
44     5.1
46     5.1
117    7.7
131    7.9
Name: sepal length (cm), dtype: float64
passed in length 6 return length =1 scalar ()
return value 6.1000000000000005
----
----
Passed in -- <class 'pandas.core.series.Series'>
18     1.7
19     1.5
44     1.9
46     1.6
117    6.7
131    6.4
Name: petal length (cm), dtype: float64
passed in length 6 return length =1 scalar ()
return value 3.2999999999999994
----
----
Passed in -- <class 'pandas.core.series.Series'>
18     0.3
19     0.3
44     0.4
46     0.2
117    2.2
131    2.0
Name: petal width (cm), dtype: float64
passed in length 6 return length =1 scalar ()
return value 0.9
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  petal length (cm)  petal width (cm)
18                 5.7                1.7               0.3
19                 5.1                1.5               0.3
44                 5.1                1.9               0.4
46                 5.1                1.6               0.2
117                7.7                6.7               2.2
131                7.9                6.4               2.0
passed in length 6 return length =1 scalar (3,)
return value sepal length (cm)    6.1
petal length (cm)    3.3
petal width (cm)     0.9
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
5     5.4
16    5.4
Name: sepal length (cm), dtype: float64
passed in length 2 return length =1 scalar ()
return value 5.4
----
----
Passed in -- <class 'pandas.core.series.Series'>
5     1.7
16    1.3
Name: petal length (cm), dtype: float64
passed in length 2 return length =1 scalar ()
return value 1.5
----
----
Passed in -- <class 'pandas.core.series.Series'>
5     0.4
16    0.4
Name: petal width (cm), dtype: float64
passed in length 2 return length =1 scalar ()
return value 0.4
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
5                 5.4                1.7               0.4
16                5.4                1.3               0.4
passed in length 2 return length =1 scalar (3,)
return value sepal length (cm)    5.4
petal length (cm)    1.5
petal width (cm)     0.4
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
14    5.8
Name: sepal length (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 5.8
----
----
Passed in -- <class 'pandas.core.series.Series'>
14    1.2
Name: petal length (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 1.2
----
----
Passed in -- <class 'pandas.core.series.Series'>
14    0.2
Name: petal width (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 0.2
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
14                5.8                1.2               0.2
passed in length 1 return length =1 scalar (3,)
return value sepal length (cm)    5.8
petal length (cm)    1.2
petal width (cm)     0.2
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
32    5.2
Name: sepal length (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 5.2
----
----
Passed in -- <class 'pandas.core.series.Series'>
32    1.5
Name: petal length (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 1.5
----
----
Passed in -- <class 'pandas.core.series.Series'>
32    0.1
Name: petal width (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 0.1
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
32                5.2                1.5               0.1
passed in length 1 return length =1 scalar (3,)
return value sepal length (cm)    5.2
petal length (cm)    1.5
petal width (cm)     0.1
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
33    5.5
Name: sepal length (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 5.5
----
----
Passed in -- <class 'pandas.core.series.Series'>
33    1.4
Name: petal length (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 1.4
----
----
Passed in -- <class 'pandas.core.series.Series'>
33    0.2
Name: petal width (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 0.2
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
33                5.5                1.4               0.2
passed in length 1 return length =1 scalar (3,)
return value sepal length (cm)    5.5
petal length (cm)    1.4
petal width (cm)     0.2
dtype: float64
----
----
Passed in -- <class 'pandas.core.series.Series'>
15    5.7
Name: sepal length (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 5.7
----
----
Passed in -- <class 'pandas.core.series.Series'>
15    1.5
Name: petal length (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 1.5
----
----
Passed in -- <class 'pandas.core.series.Series'>
15    0.4
Name: petal width (cm), dtype: float64
passed in length 1 return length =1 scalar ()
return value 0.4
----
----
Passed in -- <class 'pandas.core.frame.DataFrame'>
    sepal length (cm)  petal length (cm)  petal width (cm)
15                5.7                1.5               0.4
passed in length 1 return length =1 scalar (3,)
return value sepal length (cm)    5.7
petal length (cm)    1.5
petal width (cm)     0.4
dtype: float64
----
     sepal length (cm)  petal length (cm)  petal width (cm)
0             5.150000           1.416667          0.300000
1             6.015385           4.234615          1.403846
2             5.884615           3.753846          1.261538
3             6.036364           3.790909          1.245455
4             5.425000           2.475000          0.750000
..                 ...                ...               ...
145           6.015385           4.234615          1.403846
146           5.762500           4.512500          1.550000
147           6.015385           4.234615          1.403846
148           5.316667           2.466667          0.716667
149           6.015385           4.234615          1.403846

[150 rows x 3 columns]
     sepal length (cm)  petal length (cm)  petal width (cm)
62            6.066667                4.5          1.333333
68            6.066667                4.5          1.333333
119           6.066667                4.5          1.333333

In [38]:
groups=df.groupby(df.columns[1])

#print(groups.get_group(2.0).transform(add))
for name,group in groups:
    print(name)
    print()
    print(type(group))
    #print(group.head(2))
    print()
    print(group.transform(add))

2.0

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
60    5.0
Name: sepal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
60    2.0
Name: sepal width (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
60    3.5
Name: petal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
60    1.0
Name: petal width (cm), dtype: float64
Passed in length 1 return length 1
----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
60               15.0              12.0               13.5              11.0
2.2

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
62     6.0
68     6.2
119    6.0
Name: sepal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
62     2.2
68     2.2
119    2.2
Name: sepal width (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
62     4.0
68     4.5
119    5.0
Name: petal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
62     1.0
68     1.5
119    1.5
Name: petal width (cm), dtype: float64
Passed in length 3 return length 3
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
62                16.0              12.2               14.0              11.0
68                16.2              12.2               14.5              11.5
119               16.0              12.2               15.0              11.5
2.3

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
41    4.5
53    5.5
87    6.3
93    5.0
Name: sepal length (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
41    2.3
53    2.3
87    2.3
93    2.3
Name: sepal width (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
41    1.3
53    4.0
87    4.4
93    3.3
Name: petal length (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
41    0.3
53    1.3
87    1.3
93    1.0
Name: petal width (cm), dtype: float64
Passed in length 4 return length 4
----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
41               14.5              12.3               11.3              10.3
53               15.5              12.3               14.0              11.3
87               16.3              12.3               14.4              11.3
93               15.0              12.3               13.3              11.0
2.4

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
57    4.9
80    5.5
81    5.5
Name: sepal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
57    2.4
80    2.4
81    2.4
Name: sepal width (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
57    3.3
80    3.8
81    3.7
Name: petal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
57    1.0
80    1.1
81    1.0
Name: petal width (cm), dtype: float64
Passed in length 3 return length 3
----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
57               14.9              12.4               13.3              11.0
80               15.5              12.4               13.8              11.1
81               15.5              12.4               13.7              11.0
2.5

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
69     5.6
72     6.3
89     5.5
98     5.1
106    4.9
108    6.7
113    5.7
146    6.3
Name: sepal length (cm), dtype: float64
Passed in length 8 return length 8
----
----
Passed in -- <class 'pandas.core.series.Series'>
69     2.5
72     2.5
89     2.5
98     2.5
106    2.5
108    2.5
113    2.5
146    2.5
Name: sepal width (cm), dtype: float64
Passed in length 8 return length 8
----
----
Passed in -- <class 'pandas.core.series.Series'>
69     3.9
72     4.9
89     4.0
98     3.0
106    4.5
108    5.8
113    5.0
146    5.0
Name: petal length (cm), dtype: float64
Passed in length 8 return length 8
----
----
Passed in -- <class 'pandas.core.series.Series'>
69     1.1
72     1.5
89     1.3
98     1.1
106    1.7
108    1.8
113    2.0
146    1.9
Name: petal width (cm), dtype: float64
Passed in length 8 return length 8
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
69                15.6              12.5               13.9              11.1
72                16.3              12.5               14.9              11.5
89                15.5              12.5               14.0              11.3
98                15.1              12.5               13.0              11.1
106               14.9              12.5               14.5              11.7
108               16.7              12.5               15.8              11.8
113               15.7              12.5               15.0              12.0
146               16.3              12.5               15.0              11.9
2.6

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
79     5.7
90     5.5
92     5.8
118    7.7
134    6.1
Name: sepal length (cm), dtype: float64
Passed in length 5 return length 5
----
----
Passed in -- <class 'pandas.core.series.Series'>
79     2.6
90     2.6
92     2.6
118    2.6
134    2.6
Name: sepal width (cm), dtype: float64
Passed in length 5 return length 5
----
----
Passed in -- <class 'pandas.core.series.Series'>
79     3.5
90     4.4
92     4.0
118    6.9
134    5.6
Name: petal length (cm), dtype: float64
Passed in length 5 return length 5
----
----
Passed in -- <class 'pandas.core.series.Series'>
79     1.0
90     1.2
92     1.2
118    2.3
134    1.4
Name: petal width (cm), dtype: float64
Passed in length 5 return length 5
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
79                15.7              12.6               13.5              11.0
90                15.5              12.6               14.4              11.2
92                15.8              12.6               14.0              11.2
118               17.7              12.6               16.9              12.3
134               16.1              12.6               15.6              11.4
2.7

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
59     5.2
67     5.8
82     5.8
83     6.0
94     5.6
101    5.8
111    6.4
123    6.3
142    5.8
Name: sepal length (cm), dtype: float64
Passed in length 9 return length 9
----
----
Passed in -- <class 'pandas.core.series.Series'>
59     2.7
67     2.7
82     2.7
83     2.7
94     2.7
101    2.7
111    2.7
123    2.7
142    2.7
Name: sepal width (cm), dtype: float64
Passed in length 9 return length 9
----
----
Passed in -- <class 'pandas.core.series.Series'>
59     3.9
67     4.1
82     3.9
83     5.1
94     4.2
101    5.1
111    5.3
123    4.9
142    5.1
Name: petal length (cm), dtype: float64
Passed in length 9 return length 9
----
----
Passed in -- <class 'pandas.core.series.Series'>
59     1.4
67     1.0
82     1.2
83     1.6
94     1.3
101    1.9
111    1.9
123    1.8
142    1.9
Name: petal width (cm), dtype: float64
Passed in length 9 return length 9
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
59                15.2              12.7               13.9              11.4
67                15.8              12.7               14.1              11.0
82                15.8              12.7               13.9              11.2
83                16.0              12.7               15.1              11.6
94                15.6              12.7               14.2              11.3
101               15.8              12.7               15.1              11.9
111               16.4              12.7               15.3              11.9
123               16.3              12.7               14.9              11.8
142               15.8              12.7               15.1              11.9
2.8

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
54     6.5
55     5.7
71     6.1
73     6.1
76     6.8
99     5.7
114    5.8
121    5.6
122    7.7
126    6.2
128    6.4
130    7.4
132    6.4
133    6.3
Name: sepal length (cm), dtype: float64
Passed in length 14 return length 14
----
----
Passed in -- <class 'pandas.core.series.Series'>
54     2.8
55     2.8
71     2.8
73     2.8
76     2.8
99     2.8
114    2.8
121    2.8
122    2.8
126    2.8
128    2.8
130    2.8
132    2.8
133    2.8
Name: sepal width (cm), dtype: float64
Passed in length 14 return length 14
----
----
Passed in -- <class 'pandas.core.series.Series'>
54     4.6
55     4.5
71     4.0
73     4.7
76     4.8
99     4.1
114    5.1
121    4.9
122    6.7
126    4.8
128    5.6
130    6.1
132    5.6
133    5.1
Name: petal length (cm), dtype: float64
Passed in length 14 return length 14
----
----
Passed in -- <class 'pandas.core.series.Series'>
54     1.5
55     1.3
71     1.3
73     1.2
76     1.4
99     1.3
114    2.4
121    2.0
122    2.0
126    1.8
128    2.1
130    1.9
132    2.2
133    1.5
Name: petal width (cm), dtype: float64
Passed in length 14 return length 14
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
54                16.5              12.8               14.6              11.5
55                15.7              12.8               14.5              11.3
71                16.1              12.8               14.0              11.3
73                16.1              12.8               14.7              11.2
76                16.8              12.8               14.8              11.4
99                15.7              12.8               14.1              11.3
114               15.8              12.8               15.1              12.4
121               15.6              12.8               14.9              12.0
122               17.7              12.8               16.7              12.0
126               16.2              12.8               14.8              11.8
128               16.4              12.8               15.6              12.1
130               17.4              12.8               16.1              11.9
132               16.4              12.8               15.6              12.2
133               16.3              12.8               15.1              11.5
2.9

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
8      4.4
58     6.6
63     6.1
64     5.6
74     6.4
78     6.0
96     5.7
97     6.2
103    6.3
107    7.3
Name: sepal length (cm), dtype: float64
Passed in length 10 return length 10
----
----
Passed in -- <class 'pandas.core.series.Series'>
8      2.9
58     2.9
63     2.9
64     2.9
74     2.9
78     2.9
96     2.9
97     2.9
103    2.9
107    2.9
Name: sepal width (cm), dtype: float64
Passed in length 10 return length 10
----
----
Passed in -- <class 'pandas.core.series.Series'>
8      1.4
58     4.6
63     4.7
64     3.6
74     4.3
78     4.5
96     4.2
97     4.3
103    5.6
107    6.3
Name: petal length (cm), dtype: float64
Passed in length 10 return length 10
----
----
Passed in -- <class 'pandas.core.series.Series'>
8      0.2
58     1.3
63     1.4
64     1.3
74     1.3
78     1.5
96     1.3
97     1.3
103    1.8
107    1.8
Name: petal width (cm), dtype: float64
Passed in length 10 return length 10
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                 14.4              12.9               11.4              10.2
58                16.6              12.9               14.6              11.3
63                16.1              12.9               14.7              11.4
64                15.6              12.9               13.6              11.3
74                16.4              12.9               14.3              11.3
78                16.0              12.9               14.5              11.5
96                15.7              12.9               14.2              11.3
97                16.2              12.9               14.3              11.3
103               16.3              12.9               15.6              11.8
107               17.3              12.9               16.3              11.8
3.0

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
1      4.9
12     4.8
13     4.3
25     5.0
38     4.4
45     4.8
61     5.9
66     5.6
75     6.6
77     6.7
84     5.4
88     5.6
91     6.1
95     5.7
102    7.1
104    6.5
105    7.6
112    6.8
116    6.5
127    6.1
129    7.2
135    7.7
138    6.0
145    6.7
147    6.5
149    5.9
Name: sepal length (cm), dtype: float64
Passed in length 26 return length 26
----
----
Passed in -- <class 'pandas.core.series.Series'>
1      3.0
12     3.0
13     3.0
25     3.0
38     3.0
45     3.0
61     3.0
66     3.0
75     3.0
77     3.0
84     3.0
88     3.0
91     3.0
95     3.0
102    3.0
104    3.0
105    3.0
112    3.0
116    3.0
127    3.0
129    3.0
135    3.0
138    3.0
145    3.0
147    3.0
149    3.0
Name: sepal width (cm), dtype: float64
Passed in length 26 return length 26
----
----
Passed in -- <class 'pandas.core.series.Series'>
1      1.4
12     1.4
13     1.1
25     1.6
38     1.3
45     1.4
61     4.2
66     4.5
75     4.4
77     5.0
84     4.5
88     4.1
91     4.6
95     4.2
102    5.9
104    5.8
105    6.6
112    5.5
116    5.5
127    4.9
129    5.8
135    6.1
138    4.8
145    5.2
147    5.2
149    5.1
Name: petal length (cm), dtype: float64
Passed in length 26 return length 26
----
----
Passed in -- <class 'pandas.core.series.Series'>
1      0.2
12     0.1
13     0.1
25     0.2
38     0.2
45     0.3
61     1.5
66     1.5
75     1.4
77     1.7
84     1.5
88     1.3
91     1.4
95     1.2
102    2.1
104    2.2
105    2.1
112    2.1
116    1.8
127    1.8
129    1.6
135    2.3
138    1.8
145    2.3
147    2.0
149    1.8
Name: petal width (cm), dtype: float64

Passed in length 26 return length 26
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                 14.9              13.0               11.4              10.2
12                14.8              13.0               11.4              10.1
13                14.3              13.0               11.1              10.1
25                15.0              13.0               11.6              10.2
38                14.4              13.0               11.3              10.2
45                14.8              13.0               11.4              10.3
61                15.9              13.0               14.2              11.5
66                15.6              13.0               14.5              11.5
75                16.6              13.0               14.4              11.4
77                16.7              13.0               15.0              11.7
84                15.4              13.0               14.5              11.5
88                15.6              13.0               14.1              11.3
91                16.1              13.0               14.6              11.4
95                15.7              13.0               14.2              11.2
102               17.1              13.0               15.9              12.1
104               16.5              13.0               15.8              12.2
105               17.6              13.0               16.6              12.1
112               16.8              13.0               15.5              12.1
116               16.5              13.0               15.5              11.8
127               16.1              13.0               14.9              11.8
129               17.2              13.0               15.8              11.6
135               17.7              13.0               16.1              12.3
138               16.0              13.0               14.8              11.8
145               16.7              13.0               15.2              12.3
147               16.5              13.0               15.2              12.0
149               15.9              13.0               15.1              11.8
3.1

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
3      4.6
9      4.9
30     4.8
34     4.9
52     6.9
65     6.7
86     6.7
137    6.4
139    6.9
140    6.7
141    6.9
Name: sepal length (cm), dtype: float64
Passed in length 11 return length 11
----
----
Passed in -- <class 'pandas.core.series.Series'>
3      3.1
9      3.1
30     3.1
34     3.1
52     3.1
65     3.1
86     3.1
137    3.1
139    3.1
140    3.1
141    3.1
Name: sepal width (cm), dtype: float64
Passed in length 11 return length 11
----
----
Passed in -- <class 'pandas.core.series.Series'>
3      1.5
9      1.5
30     1.6
34     1.5
52     4.9
65     4.4
86     4.7
137    5.5
139    5.4
140    5.6
141    5.1
Name: petal length (cm), dtype: float64
Passed in length 11 return length 11
----
----
Passed in -- <class 'pandas.core.series.Series'>
3      0.2
9      0.1
30     0.2
34     0.2
52     1.5
65     1.4
86     1.5
137    1.8
139    2.1
140    2.4
141    2.3
Name: petal width (cm), dtype: float64
Passed in length 11 return length 11
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
3                 14.6              13.1               11.5              10.2
9                 14.9              13.1               11.5              10.1
30                14.8              13.1               11.6              10.2
34                14.9              13.1               11.5              10.2
52                16.9              13.1               14.9              11.5
65                16.7              13.1               14.4              11.4
86                16.7              13.1               14.7              11.5
137               16.4              13.1               15.5              11.8
139               16.9              13.1               15.4              12.1
140               16.7              13.1               15.6              12.4
141               16.9              13.1               15.1              12.3
3.2

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
2      4.7
29     4.7
35     5.0
42     4.4
47     4.6
50     7.0
51     6.4
70     5.9
110    6.5
115    6.4
120    6.9
125    7.2
143    6.8
Name: sepal length (cm), dtype: float64
Passed in length 13 return length 13
----
----
Passed in -- <class 'pandas.core.series.Series'>
2      3.2
29     3.2
35     3.2
42     3.2
47     3.2
50     3.2
51     3.2
70     3.2
110    3.2
115    3.2
120    3.2
125    3.2
143    3.2
Name: sepal width (cm), dtype: float64
Passed in length 13 return length 13
----
----
Passed in -- <class 'pandas.core.series.Series'>
2      1.3
29     1.6
35     1.2
42     1.3
47     1.4
50     4.7
51     4.5
70     4.8
110    5.1
115    5.3
120    5.7
125    6.0
143    5.9
Name: petal length (cm), dtype: float64
Passed in length 13 return length 13
----
----
Passed in -- <class 'pandas.core.series.Series'>
2      0.2
29     0.2
35     0.2
42     0.2
47     0.2
50     1.4
51     1.5
70     1.8
110    2.0
115    2.3
120    2.3
125    1.8
143    2.3
Name: petal width (cm), dtype: float64
Passed in length 13 return length 13
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
2                 14.7              13.2               11.3              10.2
29                14.7              13.2               11.6              10.2
35                15.0              13.2               11.2              10.2
42                14.4              13.2               11.3              10.2
47                14.6              13.2               11.4              10.2
50                17.0              13.2               14.7              11.4
51                16.4              13.2               14.5              11.5
70                15.9              13.2               14.8              11.8
110               16.5              13.2               15.1              12.0
115               16.4              13.2               15.3              12.3
120               16.9              13.2               15.7              12.3
125               17.2              13.2               16.0              11.8
143               16.8              13.2               15.9              12.3
3.3

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
23     5.1
49     5.0
56     6.3
100    6.3
124    6.7
144    6.7
Name: sepal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
23     3.3
49     3.3
56     3.3
100    3.3
124    3.3
144    3.3
Name: sepal width (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
23     1.7
49     1.4
56     4.7
100    6.0
124    5.7
144    5.7
Name: petal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
23     0.5
49     0.2
56     1.6
100    2.5
124    2.1
144    2.5
Name: petal width (cm), dtype: float64
Passed in length 6 return length 6
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
23                15.1              13.3               11.7              10.5
49                15.0              13.3               11.4              10.2
56                16.3              13.3               14.7              11.6
100               16.3              13.3               16.0              12.5
124               16.7              13.3               15.7              12.1
144               16.7              13.3               15.7              12.5
3.4

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
6      4.6
7      5.0
11     4.8
20     5.4
24     4.8
26     5.0
28     5.2
31     5.4
39     5.1
85     6.0
136    6.3
148    6.2
Name: sepal length (cm), dtype: float64
Passed in length 12 return length 12
----
----
Passed in -- <class 'pandas.core.series.Series'>
6      3.4
7      3.4
11     3.4
20     3.4
24     3.4
26     3.4
28     3.4
31     3.4
39     3.4
85     3.4
136    3.4
148    3.4
Name: sepal width (cm), dtype: float64
Passed in length 12 return length 12
----
----
Passed in -- <class 'pandas.core.series.Series'>
6      1.4
7      1.5
11     1.6
20     1.7
24     1.9
26     1.6
28     1.4
31     1.5
39     1.5
85     4.5
136    5.6
148    5.4
Name: petal length (cm), dtype: float64
Passed in length 12 return length 12
----
----
Passed in -- <class 'pandas.core.series.Series'>
6      0.3
7      0.2
11     0.2
20     0.2
24     0.2
26     0.4
28     0.2
31     0.4
39     0.2
85     1.6
136    2.4
148    2.3
Name: petal width (cm), dtype: float64
Passed in length 12 return length 12
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
6                 14.6              13.4               11.4              10.3
7                 15.0              13.4               11.5              10.2
11                14.8              13.4               11.6              10.2
20                15.4              13.4               11.7              10.2
24                14.8              13.4               11.9              10.2
26                15.0              13.4               11.6              10.4
28                15.2              13.4               11.4              10.2
31                15.4              13.4               11.5              10.4
39                15.1              13.4               11.5              10.2
85                16.0              13.4               14.5              11.6
136               16.3              13.4               15.6              12.4
148               16.2              13.4               15.4              12.3
3.5

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
0     5.1
17    5.1
27    5.2
36    5.5
40    5.0
43    5.0
Name: sepal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
0     3.5
17    3.5
27    3.5
36    3.5
40    3.5
43    3.5
Name: sepal width (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
0     1.4
17    1.4
27    1.5
36    1.3
40    1.3
43    1.6
Name: petal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
0     0.2
17    0.3
27    0.2
36    0.2
40    0.3
43    0.6
Name: petal width (cm), dtype: float64
Passed in length 6 return length 6
----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                15.1              13.5               11.4              10.2
17               15.1              13.5               11.4              10.3
27               15.2              13.5               11.5              10.2
36               15.5              13.5               11.3              10.2
40               15.0              13.5               11.3              10.3
43               15.0              13.5               11.6              10.6
3.6

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
4      5.0
22     4.6
37     4.9
109    7.2
Name: sepal length (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
4      3.6
22     3.6
37     3.6
109    3.6
Name: sepal width (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
4      1.4
22     1.0
37     1.4
109    6.1
Name: petal length (cm), dtype: float64
Passed in length 4 return length 4
----
----
Passed in -- <class 'pandas.core.series.Series'>
4      0.2
22     0.2
37     0.1
109    2.5
Name: petal width (cm), dtype: float64
Passed in length 4 return length 4
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
4                 15.0              13.6               11.4              10.2
22                14.6              13.6               11.0              10.2
37                14.9              13.6               11.4              10.1
109               17.2              13.6               16.1              12.5
3.7

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
10    5.4
21    5.1
48    5.3
Name: sepal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
10    3.7
21    3.7
48    3.7

Name: sepal width (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
10    1.5
21    1.5
48    1.5
Name: petal length (cm), dtype: float64
Passed in length 3 return length 3
----
----
Passed in -- <class 'pandas.core.series.Series'>
10    0.2
21    0.4
48    0.2
Name: petal width (cm), dtype: float64
Passed in length 3 return length 3
----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
10               15.4              13.7               11.5              10.2
21               15.1              13.7               11.5              10.4
48               15.3              13.7               11.5              10.2
3.8

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
18     5.7
19     5.1
44     5.1
46     5.1
117    7.7
131    7.9
Name: sepal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
18     3.8
19     3.8
44     3.8
46     3.8
117    3.8
131    3.8
Name: sepal width (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
18     1.7
19     1.5
44     1.9
46     1.6
117    6.7
131    6.4
Name: petal length (cm), dtype: float64
Passed in length 6 return length 6
----
----
Passed in -- <class 'pandas.core.series.Series'>
18     0.3
19     0.3
44     0.4
46     0.2
117    2.2
131    2.0
Name: petal width (cm), dtype: float64
Passed in length 6 return length 6
----
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
18                15.7              13.8               11.7              10.3
19                15.1              13.8               11.5              10.3
44                15.1              13.8               11.9              10.4
46                15.1              13.8               11.6              10.2
117               17.7              13.8               16.7              12.2
131               17.9              13.8               16.4              12.0
3.9

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
5     5.4
16    5.4
Name: sepal length (cm), dtype: float64
Passed in length 2 return length 2
----
----
Passed in -- <class 'pandas.core.series.Series'>
5     3.9
16    3.9
Name: sepal width (cm), dtype: float64
Passed in length 2 return length 2
----
----
Passed in -- <class 'pandas.core.series.Series'>
5     1.7
16    1.3
Name: petal length (cm), dtype: float64
Passed in length 2 return length 2
----
----
Passed in -- <class 'pandas.core.series.Series'>
5     0.4
16    0.4
Name: petal width (cm), dtype: float64
Passed in length 2 return length 2
----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
5                15.4              13.9               11.7              10.4
16               15.4              13.9               11.3              10.4
4.0

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
14    5.8
Name: sepal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
14    4.0
Name: sepal width (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
14    1.2
Name: petal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
14    0.2
Name: petal width (cm), dtype: float64
Passed in length 1 return length 1
----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
14               15.8              14.0               11.2              10.2
4.1

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
32    5.2
Name: sepal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
32    4.1
Name: sepal width (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
32    1.5
Name: petal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
32    0.1
Name: petal width (cm), dtype: float64
Passed in length 1 return length 1
----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
32               15.2              14.1               11.5              10.1
4.2

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
33    5.5
Name: sepal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
33    4.2
Name: sepal width (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
33    1.4
Name: petal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
33    0.2
Name: petal width (cm), dtype: float64
Passed in length 1 return length 1
----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
33               15.5              14.2               11.4              10.2
4.4

<class 'pandas.core.frame.DataFrame'>

----
Passed in -- <class 'pandas.core.series.Series'>
15    5.7
Name: sepal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
15    4.4
Name: sepal width (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
15    1.5
Name: petal length (cm), dtype: float64
Passed in length 1 return length 1
----
----
Passed in -- <class 'pandas.core.series.Series'>
15    0.4
Name: petal width (cm), dtype: float64
Passed in length 1 return length 1
----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
15               15.7              14.4               11.5              10.4